<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7f2443214171: ccl_err + 0x8171 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb1)
	0x7f2443217015: ccl_err + 0xb015 (_Z14err_terminatorv + 0x4b)
	0x7f243b39f796: stdc++.so.6 + 0x63796 (_ZN10__cxxabiv111__terminateEPFvvE + 0x6)
	0x7f243b39f7c3: stdc++.so.6 + 0x637c3
	0x7f243b39fa36: stdc++.so.6 + 0x63a36 (__cxa_rethrow + 0x46)
	0x7f2466c07b64: QtCore.so.4 + 0x1a5b64 (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x2f4)
	0x7f2466c0c7c4: QtCore.so.4 + 0x1aa7c4 (_ZN16QCoreApplication4execEv + 0xb4)
	   0x401ea8: quartus + 0x1ea8 (_Z8qgq_mainiPPKc + 0x68)
	0x7f2445a827e0: ccl_msg + 0x407e0 (_Z15msg_main_threadPv + 0x10)
	0x7f2442dd402c: ccl_thr + 0x602c (thr_final_wrapper + 0xc)
	0x7f2445a8289f: ccl_msg + 0x4089f (_Z18msg_thread_wrapperPFPvS_ES_ + 0x62)
	0x7f2443447559: ccl_mem + 0xa559 (_Z18mem_thread_wrapperPFPvS_ES_ + 0x99)
	0x7f2443214f92: ccl_err + 0x8f92 (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7f2442dd43f2: ccl_thr + 0x63f2 (thr_thread_wrapper + 0x15)
	0x7f2445a84c37: ccl_msg + 0x42c37 (_Z12msg_exe_mainiPPKcPFiiS1_E + 0xa3)
	   0x401f7a: quartus + 0x1f7a (main + 0x26)
	0x7f243ac2f152: c.so.6 + 0x28152 (__libc_start_main + 0xf2)
	   0x401d59: quartus + 0x1d59
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Sun Oct 18 17:35:23 2020
</date>
<version>Version 16.1.2 Build 203 01/18/2017 SJ Standard Edition</version>
</internal_error>